### ISSUE TITLE
画面構成を決める。

### ISSUE THREAD

**Issue by NakataTPD** [NakataTPD/k-web-training#1]
作成する画面を決めて、画面一覧を作成してください。
マークダウンファイルで作成して下さい。
※マークダウンはdocumentの下に作成してください。
※ローカルマシンにSourceTreeをインストールして、developブランチから作成したfuture/createScreensListブランチをプッシュ＆プルリクしてください。

 - [x] SourceTreeのインストール
 - [x] 画面一覧作成
 - [x] 自己レビュー
 - [x] レビュー

**Comment by NakataTPD** [comment]
指摘
1. featureブランチを別名で再作成し下記2以降の指摘を修正して、再度コミット→プッシュ→プルリクして下さい。
2. 登録後、変更後、削除後にどの画面に遷移するか表現して下さい。
3. 変更画面で削除可能になっていますが、変更画面は入力可能画面であり、削除時に入力は必要ないため、一覧または詳細画面で削除可能とした方がよいです。
4. 画面一覧の中の画面遷移図画像のリンクが切れているようです。
5. 詳細画面の英名（オブジェクト名？）ですが、「PaiDetailList」となってます。List？
6. 画面一覧項目のオブジェクト名っていう文言ですが、なんか違和感あるので、英名とかhtml名とかでいいと思います。

**Comment by KashiwagiTPD** [comment]
指摘1.～6.の修正を行いました。
