### ISSUE TITLE
どのようなWebシステムを作るか決める。

### ISSUE THREAD

**Issue by NakataTPD** [NakataTPD/k-web-training#2]
### 前提
 - CRUD機能をもつこと。

WikiのHomeのシステム名と機能概要を修正してください。
※GithubのWikiはどのようなことを書くのか、どんな表現ができるのか、一般的な構成など、実際に公開されている他のパブリックリポジトリを覗いてみてください。

**Comment by KashiwagiTPD** [comment]
* 2019/11/08 更新が完了しました。

**Comment by NakataTPD** [comment]
To: @KashiwagiTPD 
以下、現Wikiの指摘です。
1.”マスタ作成機能”と”マスタ登録機能”を分けた理由はありますか？同じでいいような。。
2.変更機能も追加してください。

**Comment by KashiwagiTPD** [comment]
2019/11/18 更新が完了しました。  
1.→マスタ登録機能。マスタ一括登録機能という形にしました。  
2.→変更機能追加しました。

**Comment by NakataTPD** [comment]
To: @KashiwagiTPD
機能概要ですが、機能一覧と内容が同じようなので、まるっと削除してください。
（機能名が概要と一覧で違うものがあったりと、メンテも手間だと思いますので。）

**Comment by KashiwagiTPD** [comment]
2019/11/22 更新が完了しました。
＞機能概要ですが、機能一覧と内容が同じようなので、まるっと削除してください。
→機能概要と機能一覧を合体しました。

**Comment by NakataTPD** [comment]
> 2019/11/22 更新が完了しました。
> ＞機能概要ですが、機能一覧と内容が同じようなので、まるっと削除してください。
> →機能概要と機能一覧を合体しました。

👍
